#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Integration script to enable the new stable data source system.

This script patches the existing app.py to use the new multi-source aggregator
while maintaining backward compatibility.

Usage:
    python enable_stable_sources.py --mode test     # Test mode (dry run)
    python enable_stable_sources.py --mode enable   # Enable new system
    python enable_stable_sources.py --mode rollback # Rollback to old system
"""
import argparse
import sys
from pathlib import Path


INTEGRATION_CODE = '''
# ============================================================================
# Enhanced data source integration (auto-generated by enable_stable_sources.py)
# ============================================================================
import os
USE_STABLE_DATA_SOURCES = os.getenv("USE_STABLE_DATA_SOURCES", "true").lower() == "true"

if USE_STABLE_DATA_SOURCES:
    print("[data-service] Using stable multi-source data system")
    from data_service_v2 import (
        fetch_spot as fetch_spot_v2,
        fetch_kline as fetch_kline_v2,
        fetch_minute_kline as fetch_minute_kline_v2,
        get_sources_health_sync,
    )

    # Monkey-patch the existing functions
    _original_fetch_spot = fetch_spot
    _original_fetch_stock_daily = fetch_stock_daily
    _original_fetch_stock_hourly = fetch_stock_hourly

    def fetch_spot():
        """Enhanced fetch_spot with multi-source fallback."""
        try:
            df = fetch_spot_v2()
            # Convert column names to Chinese if needed
            if not df.empty and "code" in df.columns:
                rename = {
                    "code": "代码", "name": "名称", "price": "最新价",
                    "pct_change": "涨跌幅", "market_cap_yi": "总市值_亿",
                    "industry": "行业", "volume": "成交量", "amount": "成交额",
                }
                df = df.rename(columns={k: v for k, v in rename.items() if k in df.columns})
            return df
        except Exception as e:
            print(f"[data-service] fetch_spot_v2 failed: {e}, falling back to original")
            return _original_fetch_spot()

    def fetch_stock_daily(code: str, days: int = 250, adjust: str = "qfq"):
        """Enhanced fetch_stock_daily with multi-source fallback."""
        try:
            df = fetch_kline_v2(code, period="daily", count=days)
            # Convert column names to Chinese
            if not df.empty and "trade_date" in df.columns:
                rename = {
                    "trade_date": "日期", "open": "开盘", "close": "收盘",
                    "high": "最高", "low": "最低", "volume": "成交量",
                }
                df = df.rename(columns={k: v for k, v in rename.items() if k in df.columns})
            return df
        except Exception as e:
            print(f"[data-service] fetch_kline_v2 failed: {e}, falling back to original")
            return _original_fetch_stock_daily(code, days, adjust)

    def fetch_stock_hourly(code: str, count: int = 250, adjust: str = "qfq"):
        """Enhanced fetch_stock_hourly with multi-source fallback."""
        try:
            df = fetch_minute_kline_v2(code, period="60min", count=count)
            # Convert column names to Chinese
            if not df.empty and "dt" in df.columns:
                rename = {
                    "dt": "日期", "open": "开盘", "close": "收盘",
                    "high": "最高", "low": "最低", "volume": "成交量",
                }
                df = df.rename(columns={k: v for k, v in rename.items() if k in df.columns})
            return df
        except Exception as e:
            print(f"[data-service] fetch_minute_kline_v2 failed: {e}, falling back to original")
            return _original_fetch_stock_hourly(code, count, adjust)

    # Add health check endpoint
    @app.route("/api/data-sources/health")
    def data_sources_health():
        try:
            health = get_sources_health_sync()
            return jsonify({"sources": health, "enabled": True})
        except Exception as e:
            return jsonify({"error": str(e), "enabled": True}), 500
else:
    print("[data-service] Using legacy data sources")
# ============================================================================
# End of enhanced data source integration
# ============================================================================
'''


def find_app_py():
    """Find app.py in the current directory."""
    candidates = [
        Path(__file__).parent / "app.py",
        Path.cwd() / "app.py",
    ]
    for p in candidates:
        if p.exists():
            return p
    raise FileNotFoundError("Could not find app.py")


def enable_stable_sources(dry_run=False):
    """Enable stable data sources by patching app.py."""
    app_py = find_app_py()
    print(f"Found app.py: {app_py}")

    content = app_py.read_text(encoding="utf-8")

    # Check if already patched
    if "enable_stable_sources.py" in content:
        print("✓ Stable data sources already enabled")
        return

    # Find insertion point (after imports, before first function)
    lines = content.split("\n")
    insert_idx = 0
    for i, line in enumerate(lines):
        if line.startswith("def ") or line.startswith("@app.route"):
            insert_idx = i
            break
        if line.strip() and not line.startswith("#") and not line.startswith("import") and not line.startswith("from"):
            insert_idx = i

    # Insert integration code
    lines.insert(insert_idx, INTEGRATION_CODE)
    new_content = "\n".join(lines)

    if dry_run:
        print("\n[DRY RUN] Would insert the following code at line", insert_idx)
        print(INTEGRATION_CODE)
        return

    # Backup original
    backup = app_py.with_suffix(".py.bak")
    app_py.rename(backup)
    print(f"✓ Backed up original to {backup}")

    # Write patched version
    app_py.write_text(new_content, encoding="utf-8")
    print(f"✓ Patched {app_py}")
    print("\n✓ Stable data sources enabled!")
    print("   Set USE_STABLE_DATA_SOURCES=false to disable")
    print("   Run 'python enable_stable_sources.py --mode rollback' to revert")


def rollback():
    """Rollback to original app.py."""
    app_py = find_app_py()
    backup = app_py.with_suffix(".py.bak")

    if not backup.exists():
        print("✗ No backup found, cannot rollback")
        return

    # Restore backup
    app_py.unlink()
    backup.rename(app_py)
    print(f"✓ Rolled back to {app_py}")
    print("✓ Original data sources restored")


def test_integration():
    """Test the new data source system without modifying files."""
    print("\n" + "=" * 80)
    print(" Testing Stable Data Source System")
    print("=" * 80)

    try:
        # Import test
        print("\n[1/4] Testing imports...")
        from data_service_v2 import fetch_spot, fetch_kline
        from sources.aggregator import default_aggregator
        print("✓ All modules imported successfully")

        # Quick fetch test
        print("\n[2/4] Testing spot data fetch...")
        import asyncio
        agg = default_aggregator()
        spot = asyncio.run(agg.fetch_spot())
        if spot is not None and not spot.empty:
            print(f"✓ Spot data fetched: {len(spot)} rows")
        else:
            print("✗ Spot data fetch returned empty")

        # Test kline
        print("\n[3/4] Testing kline fetch...")
        kline = asyncio.run(agg.fetch_kline("600519", "daily", 250))
        if kline is not None and not kline.empty:
            print(f"✓ K-line fetched: {len(kline)} rows")
        else:
            print("✗ K-line fetch returned empty")

        # Test health
        print("\n[4/4] Testing health check...")
        from data_service_v2 import get_sources_health_sync
        health = get_sources_health_sync()
        print(f"✓ Health check working: {len(health)} sources tracked")
        for name, status in health.items():
            print(f"  - {name}: {status.get('health_score', 0):.1f}/100")

        print("\n" + "=" * 80)
        print("✓ All tests passed! System is ready for integration.")
        print("=" * 80)
        print("\nNext steps:")
        print("  1. Run: python enable_stable_sources.py --mode enable")
        print("  2. Restart data-service")
        print("  3. Monitor logs for '[data-service] Using stable multi-source data system'")

        return True

    except Exception as e:
        print(f"\n✗ Test failed: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Enable stable multi-source data system"
    )
    parser.add_argument(
        "--mode",
        choices=["test", "enable", "rollback"],
        default="test",
        help="Operation mode",
    )
    args = parser.parse_args()

    if args.mode == "test":
        success = test_integration()
        sys.exit(0 if success else 1)
    elif args.mode == "enable":
        enable_stable_sources(dry_run=False)
    elif args.mode == "rollback":
        rollback()


if __name__ == "__main__":
    main()
